In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## Array Operation

Element-wise operation: Array간 shape이 같을 때 일어나는 연산

In [4]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [5]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [6]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
# Dot product

test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [9]:
# Transpose

test_a = np.arange(1,7).reshape(2,3)
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [11]:
# Broadcast

test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [12]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [13]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [14]:
test_matrix * scalar

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [15]:
test_matrix / scalar

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [16]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)

In [17]:
test_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
test_vector

array([10, 20, 30])

In [19]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [ ]:
# numpy performance - list와 numpy의 performance 비교

def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar*vector)
    return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit scalar_vector_product(scalar, vector)   # for loop을 이용한 성능
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) % scalar  # numpy를 이용한 성능