In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

## Operation Functions

In [4]:
# Sum

test_array = np.arange(1,11)
test_array.sum()

55

In [5]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
print(test_array.sum(axis=1))   # 3,4 에서 4를 기준으로 sum
print(test_array.sum(axis=0))   # 3,4 에서 3을 기준으로 sum

[10 26 42]
[15 18 21 24]


In [7]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [8]:
print(third_order_tensor.sum(axis=2))
print(third_order_tensor.sum(axis=1))
print(third_order_tensor.sum(axis=0))

[[10 26 42]
 [10 26 42]
 [10 26 42]]
[[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]


In [11]:
# mean & std 등등

print(test_array)
print(test_array.mean())
print(test_array.mean(axis=1))
print(test_array.mean(axis=0))
print(test_array.std())
print(test_array.std(axis=1))
print(test_array.std(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6.5
[ 2.5  6.5 10.5]
[5. 6. 7. 8.]
3.452052529534663
[1.11803399 1.11803399 1.11803399]
[3.26598632 3.26598632 3.26598632 3.26598632]


In [12]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [13]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

## Concatenate: numpy array를 합치는 함수

In [15]:
# vstack(vertical stack) 

a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
# hstack(horizontal stack)

c = np.array([[1],[2],[3]])
d = np.array([[2],[3],[4]])
np.hstack((c,d))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [29]:
# concatenate: axis를 기준으로 합침

a = np.array([[1,2,3]]) # (3,1)
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [30]:
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [32]:
c = np.array([[1,2],[3,4]])
d = np.array([[5],[6]])
np.concatenate((c,d), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [33]:
e = np.array([[1,2],[3,4]])
f = np.array([[5,6]])
np.concatenate((e,f), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
np.concatenate((e,f.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [35]:
e = np.array([[1,2],[3,4]])
f = np.array([5,6])     # 1-dimension
f = f[np.newaxis, :]    # 축을 추가 시켜줌
np.concatenate((e,f.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])