In [3]:
import numpy as np

In [7]:
# reshape: changing the size of the array with the same number of elements

test_matrix = [[1,2,3,4],[5,6,7,8]]
np.array(test_matrix).shape

(2, 4)

In [8]:
np.array(test_matrix).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.array(test_matrix).reshape(2,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
# flatten: reshape multi-dimensional array to 1-dimensional array

test_tensor = [
    [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],
    [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],
    [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],
    [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
]
test_tensor = np.array(test_tensor)
print(test_tensor.flatten().size)
print(test_tensor.flatten().shape)

100
(100,)


## Indexing

In [13]:
test_example = np.array([[1,2,3],[4,5.5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
test_example[0][2]

3

In [15]:
test_example[0,2]

3

In [16]:
test_example[0,0] = 10
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [17]:
test_example[1][2] = 99
test_example

array([[10,  2,  3],
       [ 4,  5, 99]])

## Slicing

In [18]:
test_example = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
test_example = np.array(test_example, int)

In [19]:
test_example[:, 2:] # Row: All, Column: 2~

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [20]:
test_example[:,1:3].shape

(4, 2)

In [21]:
test_example[1:2, :2]   # Row: 1, Column: 0, 1

array([[5, 6]])

In [24]:
test_matrix[1]      # 1Row의 값

[5, 6, 7, 8]

In [25]:
test_matrix[1:3]    # 1Row ~ 2Row 값

[[5, 6, 7, 8]]

In [26]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
test_example[:,::3]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

In [30]:
test_example[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

## Creation Function: create an array

In [36]:
# arange

list(range(0,10,3))

[0, 3, 6, 9]

In [37]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [34]:
np.arange(30).reshape(5,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
# zeros: fills zeros inside the array

np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [40]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
# empty: leaves the array empty after making ndarray with the given size
# (no memory initialization)

np.empty(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [42]:
np.empty((3,5)) #이전의 값은 남아있고 주소값만 남게 됨

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [43]:
# something_like

test_matrix = np.arange(30).reshape(5,-1)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [44]:
# identity: 단위행렬

np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [45]:
# eye: 대각선이 1인 행렬, k값의 시작 Index 변경 가능

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.eye(3,5,k=2, dtype = np.int8)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [49]:
# diag: 대각 행렬의 값만 추출

matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [50]:
np.diag(matrix, k=1)

array([1, 5])

In [52]:
np.diag(matrix, k=-1)

array([3, 7])

In [53]:
# random sampling: 데이터의 분포

np.random.uniform(0,1,10).reshape(2,5)  #균등분포

array([[0.577671  , 0.21770559, 0.17428824, 0.47743887, 0.21148518],
       [0.02161466, 0.11823484, 0.93918004, 0.53839198, 0.2425266 ]])

In [54]:
np.random.normal(0,1,10).reshape(2,5)  #정규분포

array([[-1.43510738,  0.56536718, -0.11509372, -0.94666996,  0.81304532],
       [-0.3181529 , -0.39768   , -0.84379457,  1.35796154, -0.89967938]])

In [56]:
np.random.exponential(scale=2, size=10)

array([ 0.38588879,  1.58287965,  2.32546161, 11.98624855,  2.19842831,
        8.00465707,  1.54197341,  0.32900302,  0.40001789,  0.01578916])