In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

## numpy data i/o

In [8]:
a = np.loadtxt('input_file/population.txt')
a

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1094., 36300., 59400., 40600.]])

In [9]:
a_int = a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [10]:
np.savetxt('output_file/int_data.csv', a_int, delimiter=",")

## numpy object -npy

In [11]:
np.save("output_file/npy_test_object", arr=a_int)   #pickle 형태

In [12]:
a_test = np.load(file="output_file/npy_test_object.npy")
a_test

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500],
       [ 1903, 77400, 35200, 38200],
       [ 1094, 36300, 59400, 40600]])