In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

## Boolean Index
특정 조건에 따른 값이 True일때 배열 형태로 추출

In [8]:
test_array = np.array([1,4,0,2,8,9,7],float)
test_array > 3

array([False,  True, False, False,  True,  True,  True])

In [9]:
test_array[test_array > 3]  # True 인 index만 추출

array([4., 8., 9., 7.])

In [12]:
condition = test_array > 3
test_array[condition]

array([4., 8., 9., 7.])

In [13]:
test_array.shape

(7,)

In [14]:
(test_array > 3).shape

(7,)

## Fancy Index
array를 index value로 사용해서 값 추출

In [15]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int)    #단, 여기서 3 이상의 값이 나오면 오류가 뜸
a[b]

array([2., 2., 4., 8., 6., 4.])

In [16]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [17]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])