In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## Comparison

In [6]:
# all & any

a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
a < 4

array([ True,  True,  True,  True, False, False, False, False])

In [9]:
np.all(a<7) #모두 조건에 만족해야 True

False

In [10]:
np.any(a<5) #하나라도 조건에 만족하면 True

True

In [11]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)
test_a > test_b

array([False,  True, False])

In [12]:
test_a == test_b

array([False, False, False])

In [13]:
(test_a > test_b).any()

True

In [14]:
a = np.array([1,3,0], float)
np.logical_and(a>0, a<3)

array([ True, False, False])

In [15]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [16]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)

array([ True,  True,  True])

## np.where 
1: np.where(condition, TRUE, FALSE)    
2: np.where(condition) -> return the index

In [25]:
np.where(a>2)

(array([1]),)

In [28]:
np.where(a<2)[0]

array([0, 2])

In [24]:
np.where(a<3,3,2)

array([3, 2, 3])

In [29]:
a = np.arange(5,15)
np.where(a > 10)    #return index num

(array([6, 7, 8, 9]),)

In [30]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [31]:
np.isfinite(a)

array([ True, False, False])

In [38]:
# argmax & argmin: 최대/최소값의 index 반환

a = np.array([1,2,4,6,8,9,1,14551,1212,3])
a.argsort()

array([0, 6, 1, 9, 2, 3, 4, 5, 8, 7])

In [40]:
a.argsort()[::-1]

array([7, 8, 5, 4, 3, 2, 9, 1, 6, 0])

In [39]:
np.argmax(a)

7

In [33]:
np.argmin(a)

0

In [41]:
a[np.argmin(a)]

1

In [36]:
a = np.array([[11,2,3,4],[9,88,77,5],[12,43,65,78]])
np.argmax(a, axis=1)

array([0, 1, 3])

In [37]:
np.argmin(a, axis=0)

array([1, 0, 0, 0])