In [3]:
import numpy as np

In [4]:
# 행 벡터(Row Vector)

x = np.array([1,7,2])
x

array([1, 7, 2])

In [5]:
# 벡터의 연산(Operation in Vector)

x = np.array([1,7,2])
y = np.array([5,2,1])

In [6]:
x + y

array([6, 9, 3])

In [7]:
x - y

array([-4,  5,  1])

In [8]:
# 벡터의 성분곱(Hadamard Product)

x * y

array([ 5, 14,  2])

In [9]:
# 벡터의 노름(Norm of Vector)

# L1-norm
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

# L2-norm
def l2_norm(x):
    x_norm = x * x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

In [10]:
print(l1_norm(np.array([7,12,13])))
print(l2_norm(np.array([2,4,6,8,9])))

# L2-norm in linear algebra library
print(np.linalg.norm(np.array([2,4,6,8,9])))

32
14.177446878757825
14.177446878757825


In [11]:
# 두 벡터 사이의 각도(Angle between two vectors)

def angle(x,y):
    v = np.inner(x,y) / (l2_norm(x) * l2_norm(y))   # np.inner: 내적
    theta = np.arccos(v)
    return theta

In [12]:
angle(np.array([7,9]), np.array([1,2]))

0.197395559849881

In [13]:
angle(np.array([0,1]), np.array([0,2]))

0.0