In [16]:
# pip install sklearn

In [1]:
import numpy as np

In [2]:
# 행렬(Matrix)

X = np.array([[1,-2,3],
             [7,5,0],
             [-2,-1,2]])
X

array([[ 1, -2,  3],
       [ 7,  5,  0],
       [-2, -1,  2]])

In [3]:
# 전치 행렬(Transpose)

X.transpose()

array([[ 1,  7, -2],
       [-2,  5, -1],
       [ 3,  0,  2]])

In [5]:
X @ X.transpose()

array([[ 14,  -3,   6],
       [ -3,  74, -19],
       [  6, -19,   9]])

In [20]:
# 행렬의 곱셈(Matrix Multiplication)

X = np.array([[1,-2,3],
             [7,5,0],
             [-2,-1,2]])

Y = np.array([[0,1],
             [1,-1],
             [-2,1]])

X @ Y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [21]:
# 행렬의 내적(Inner Product of Matrix)

X = np.array([[1,-2,3],
             [7,5,0],
             [-2,-1,2]])

Y = np.array([[0,1,-1],
             [1,-1,0]])

np.inner(X,Y)

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

In [22]:
# 역행렬(Inverse Matrix)

X = np.array([[1,-2,3],
             [7,5,0],
             [-2,-1,2]])

np.linalg.inv(X)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [23]:
tmp = np.array([[1,0,1],
             [0,1,0],
             [1,1,0]])

np.linalg.inv(tmp)

array([[ 0., -1.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  1., -1.]])

In [24]:
X @ np.linalg.inv(X) # = I

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00, -5.55111512e-17],
       [ 2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [25]:
# 유사역행렬(Pseudo-Inverse Matrix)

# row와 column의 갯수가 같지 않음
Y = np.array([[0,1],
             [1,-1],
             [-2,1]])

np.linalg.pinv(Y)

array([[ 5.00000000e-01,  1.54630030e-18, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [26]:
tmp2 = np.array([[1,0,1],[0,1,0]])

np.linalg.pinv(tmp2)

array([[0.5, 0. ],
       [0. , 1. ],
       [0.5, 0. ]])

In [27]:
np.linalg.pinv(Y) @ Y # row > col => pinv(Y)@Y = I

array([[ 1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16,  1.00000000e+00]])

In [28]:
# 회귀분석(Linear Regression)

# Linear Regression using Scikit Learn - y를 자동으로 추정 & 계산
from sklearn.linear_model import LinearRegression

def linRegScikitLearn(X,y,x_test):
    model = LinearRegression()
    model.fit(X,y)
    y_test = model.predict(x_test)
    return y_test

# Linear Regression using Moore-Pensore Inverse Matrix - y를 직접 추정 & 계산
def linRegMP(X,y,x_test):
    beta = np.linalg.pinv(X) @ y
    y_test = np.append(x_test) @ beta
    return y_test