### Linear Regression based on GDM

In [1]:
import numpy as np

In [3]:
X = np.array([[1,1],[1,2],[2,2],[2,3]])
y = np.dot(X, np.array([1,2]))+3

In [21]:
beta_gd = [10.1, 15.1, -6.5]  #[1,2,3]이 정답
X_ = np.array([np.append(x,[1]) for x in X])

In [23]:
for t in range(5000):
    error = y - X_ @ beta_gd
    # error = error / np.linalg.norm(error)
    grad = - np.transpose(X_) @ error
    beta_gd = beta_gd - 0.01 * grad

print(beta_gd)

[1. 2. 3.]


In [13]:
beta_gd = [10.1, 15.1, -6.5]  #[1,2,3]이 정답
X_ = np.array([np.append(x,[1]) for x in X])

In [14]:
## GDM 에서 learning rate과 learning 횟수는 굉장히 중요한 hyperparameter
## too low -> 수렴 자체가 안 될 수도 있음 
## too high -> 수렴을 너무 늦게함 & GDM이 불안정하게 움직임

for t in range(100):
    error = y - X_ @ beta_gd
    # error = error / np.linalg.norm(error)
    grad = - np.transpose(X_) @ error
    beta_gd = beta_gd - 0.01 * grad

print(beta_gd)

[ 3.41314549  4.63604548 -6.69249764]


In [19]:
beta_gd = [10.1, 15.1, -6.5]  #[1,2,3]이 정답
X_ = np.array([np.append(x,[1]) for x in X])

In [20]:
for t in range(3000):
    error = y - X_ @ beta_gd
    error = error / np.linalg.norm(error)
    grad = - np.transpose(X_) @ error
    beta_gd = beta_gd - 0.01 * grad

print(beta_gd)

[0.98443181 1.9787477  2.99012555]
